"""fix nullable relations

Revision ID: 7de6498b9ad5
Revises: 8d8fb9552201
Create Date: 2025-10-08 21:12:52.730277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7de6498b9ad5'
down_revision: Union[str, Sequence[str], None] = '8d8fb9552201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_room_invite', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('message', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roomrole', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('roomrole', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roomrole', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('roomrole', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('message', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('chat_room_invite', 'chat_room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
