"""add unique constraint for room role

Revision ID: 8d8fb9552201
Revises: 74ec53181bcb
Create Date: 2025-10-07 16:59:48.548685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d8fb9552201'
down_revision: Union[str, Sequence[str], None] = '74ec53181bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_user_in_room', 'roomrole', ['chat_room_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_in_room', 'roomrole', type_='unique')
    # ### end Alembic commands ###
